#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef struct{
	int nodeGreen[50];
	int nodeRed[50];
}Node;

int nodeBlue[2];

void nodeInitiater(Node *a){
	int i;
	for(i=0;i<50;i++){
		a->nodeGreen[i]=0;
		a->nodeRed[i]=0;
	}
	nodeBlue[0]=0;
	nodeBlue[0]=0;
}

bool isBlack(int r, int g, int b) {
	if (r==0 && g==0 && b==0)
			return true;
		else
			return false;
}

bool isGreen(int r, int g, int b){
		if (g > (r+b))
			return true;
		else
			return false;
}

bool isRed(int r, int g, int b){
		if (r > (g + b))
			return true;
		else
			return false;
}

bool isBlue(int r, int g, int b){
		if (b > (r + g))
			return true;
		else
			return false;
}

void moveUntilBlue(){
		int r,g,b;
		bool cek=true;
		while(cek==true){
			forward(0.5, rotations, 75);
			getColorRGB(colorSensor, r, g, b);
			if (isBlue(r,g,b)){
				nodeBlue[0]=1;
				cek=false;
			}
		}
		forward(1, rotations, 75);

}

void robotRunner(Node myNode){
		bool cek=true;
		int r,g,b;
		//forward(2, rotations, 75);
		moveUntilBlue();
		while(cek==true){
			lineTrackLeft(colorSensor, 80, 80, 0);
			lineTrackRight(colorSensor, 80, 80, 0);
			//delay(1);
			getColorRGB(colorSensor, r, g, b);
			if (isGreen(r,g,b)){	//green
					setMotorSpeed(leftMotor, 50);
					sleep(500);
			}else if (isRed(r,g,b)){ //red
					stopAllMotors();
					setMotorSpeed(leftMotor, 25);
  				setMotorSpeed(rightMotor, -25);
					//lineTrackRight(colorSensor, 50, 70, 0);
			}else if (isBlue(r,g,b)){ //blue
					cek=false;
			}

     	displayTextLine(1, "red = %d",r);
     	displayTextLine(2, "green = %d",g);
     	displayTextLine(3, "blue = %d",b);
     	displayTextLine(4, "Hue = %d",getColorHue(colorSensor));
		}

}
task main()
{
	Node aa;
	nodeInitiater(&aa);
	displayTextLine(5, "nodeGreen = %d",aa.nodeGreen[2]);
	robotRunner(aa);

}
