#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void robotRunner(){
		//setMotorSpeed(leftMotor, 50);
		//setMotorSpeed(rightMotor, 50);
		bool cek=true;
		int r,g,b;
		//sleep(4000);
//		int color;
		/*while(cek==true){
			lineTrackLeft(colorSensor, 80, 60, 0);
			lineTrackRight(colorSensor, 80, 60, 0);
			//lineTrackRight(colorSensor, 0, 240, 0);
			if (getColorName(colorSensor)==colorGreen){

					setMotorSpeed(rightMotor, 50);
					setMotorSpeed(leftMotor, 50);
					sleep(500);
			}else if (getColorHue(colorSensor)>=180 && getColorHue(colorSensor)<=290){
					cek=false;
			}
		//	int r,g,b;
			//color = getColorRGB(colorSensor, r, g, b);
      //displayTextLine(1, "red = %d",r);
		}*/
		forward(2, rotations, 75);
		while(cek==true){
			lineTrackLeft(colorSensor, 80, 80, 0);
			lineTrackRight(colorSensor, 80, 80, 0);
			//delay(1);
			getColorRGB(colorSensor, r, g, b);
			if (g > (r+b)){	//green
					//setMotorSpeed(rightMotor, 50);
					setMotorSpeed(leftMotor, 50);
					sleep(500);
			}else if (r > g + b){ //red
				//	cek=false;
				//	backward(2,rotations,75);
					lineTrackRight(colorSensor, 50, 70, 0);
			}else if (b > r + g ){ //blue
					cek=false;
			}

			/*if (getColorHue(colorSensor)==85){	//green
					//setMotorSpeed(rightMotor, 50);
					setMotorSpeed(leftMotor, 50);
					sleep(500);
			}else if (getColorHue(colorSensor)==0){ //red
				//	cek=false;
					lineTrackRight(colorSensor, 50, 60, 0);
			}else if (getColorHue(colorSensor)==170){ //blue
					cek=false;
			}*/

			//getColorRGB(colorSensor, r, g, b);
     	displayTextLine(1, "red = %d",r);
     	displayTextLine(2, "green = %d",g);
     	displayTextLine(3, "blue = %d",b);
     	displayTextLine(4, "Hue = %d",getColorHue(colorSensor));
     	//displayTextLine(2, "color = %d",color);
		}

}
task main()
{
	robotRunner();
}
